# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Regression.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Regression(object):
    def setupUi(self, Regression):
        Regression.setObjectName("Regression")
        Regression.resize(1112, 642)
        self.gridLayout_4 = QtWidgets.QGridLayout(Regression)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(Regression)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(-1, 12, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BT_Reg_Excel = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.BT_Reg_Excel.setFont(font)
        self.BT_Reg_Excel.setObjectName("BT_Reg_Excel")
        self.gridLayout_3.addWidget(self.BT_Reg_Excel, 0, 2, 1, 1)
        self.label_Reg_Excel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_Reg_Excel.setFont(font)
        self.label_Reg_Excel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reg_Excel.setObjectName("label_Reg_Excel")
        self.gridLayout_3.addWidget(self.label_Reg_Excel, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 3)
        self.Tab_Regression = QtWidgets.QTabWidget(self.widget)
        self.Tab_Regression.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Tab_Regression.setFont(font)
        self.Tab_Regression.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.Tab_Regression.setObjectName("Tab_Regression")
        self.Tab_Import = QtWidgets.QWidget()
        self.Tab_Import.setObjectName("Tab_Import")
        self.gridLayout = QtWidgets.QGridLayout(self.Tab_Import)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Reg_DBC = QtWidgets.QLabel(self.Tab_Import)
        self.label_Reg_DBC.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Reg_DBC.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reg_DBC.setObjectName("label_Reg_DBC")
        self.gridLayout.addWidget(self.label_Reg_DBC, 0, 0, 1, 1)
        self.LE_Reg_DBC = QtWidgets.QLineEdit(self.Tab_Import)
        self.LE_Reg_DBC.setDragEnabled(True)
        self.LE_Reg_DBC.setReadOnly(True)
        self.LE_Reg_DBC.setObjectName("LE_Reg_DBC")
        self.gridLayout.addWidget(self.LE_Reg_DBC, 0, 1, 1, 1)
        self.BT_Reg_DBC = QtWidgets.QPushButton(self.Tab_Import)
        self.BT_Reg_DBC.setObjectName("BT_Reg_DBC")
        self.gridLayout.addWidget(self.BT_Reg_DBC, 0, 2, 1, 1)
        self.BT_Reg_ImportMsg = QtWidgets.QPushButton(self.Tab_Import)
        self.BT_Reg_ImportMsg.setObjectName("BT_Reg_ImportMsg")
        self.gridLayout.addWidget(self.BT_Reg_ImportMsg, 1, 0, 1, 1)
        self.Tab_Regression.addTab(self.Tab_Import, "")
        self.Tab_Generate = QtWidgets.QWidget()
        self.Tab_Generate.setObjectName("Tab_Generate")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Tab_Generate)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BT_Reg_DCS = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_DCS.setObjectName("BT_Reg_DCS")
        self.gridLayout_2.addWidget(self.BT_Reg_DCS, 5, 2, 1, 1)
        self.LE_Reg_IMUOutputPath = QtWidgets.QLineEdit(self.Tab_Generate)
        self.LE_Reg_IMUOutputPath.setDragEnabled(True)
        self.LE_Reg_IMUOutputPath.setReadOnly(True)
        self.LE_Reg_IMUOutputPath.setObjectName("LE_Reg_IMUOutputPath")
        self.gridLayout_2.addWidget(self.LE_Reg_IMUOutputPath, 4, 1, 1, 6)
        self.LE_Reg_ScriptTemplate = QtWidgets.QLineEdit(self.Tab_Generate)
        self.LE_Reg_ScriptTemplate.setDragEnabled(True)
        self.LE_Reg_ScriptTemplate.setReadOnly(True)
        self.LE_Reg_ScriptTemplate.setObjectName("LE_Reg_ScriptTemplate")
        self.gridLayout_2.addWidget(self.LE_Reg_ScriptTemplate, 0, 1, 1, 6)
        self.BT_Reg_CreateCurves = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_CreateCurves.setObjectName("BT_Reg_CreateCurves")
        self.gridLayout_2.addWidget(self.BT_Reg_CreateCurves, 9, 0, 1, 1)
        self.BT_Reg_ENS = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_ENS.setObjectName("BT_Reg_ENS")
        self.gridLayout_2.addWidget(self.BT_Reg_ENS, 6, 0, 1, 1)
        self.BT_Reg_GenerateAll = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_GenerateAll.setObjectName("BT_Reg_GenerateAll")
        self.gridLayout_2.addWidget(self.BT_Reg_GenerateAll, 8, 0, 1, 1)
        self.BT_Reg_CrashOutputPath = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_CrashOutputPath.setObjectName("BT_Reg_CrashOutputPath")
        self.gridLayout_2.addWidget(self.BT_Reg_CrashOutputPath, 3, 7, 1, 1)
        self.label_Reg_IMU = QtWidgets.QLabel(self.Tab_Generate)
        self.label_Reg_IMU.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reg_IMU.setObjectName("label_Reg_IMU")
        self.gridLayout_2.addWidget(self.label_Reg_IMU, 4, 0, 1, 1)
        self.BT_Reg_Loop = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_Loop.setObjectName("BT_Reg_Loop")
        self.gridLayout_2.addWidget(self.BT_Reg_Loop, 5, 0, 1, 1)
        self.BT_Reg_IMUOutputPath = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_IMUOutputPath.setObjectName("BT_Reg_IMUOutputPath")
        self.gridLayout_2.addWidget(self.BT_Reg_IMUOutputPath, 4, 7, 1, 1)
        self.LE_Reg_CrashOutputPath = QtWidgets.QLineEdit(self.Tab_Generate)
        self.LE_Reg_CrashOutputPath.setDragEnabled(True)
        self.LE_Reg_CrashOutputPath.setReadOnly(True)
        self.LE_Reg_CrashOutputPath.setObjectName("LE_Reg_CrashOutputPath")
        self.gridLayout_2.addWidget(self.LE_Reg_CrashOutputPath, 3, 1, 1, 6)
        self.label_Reg_Crash = QtWidgets.QLabel(self.Tab_Generate)
        self.label_Reg_Crash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reg_Crash.setObjectName("label_Reg_Crash")
        self.gridLayout_2.addWidget(self.label_Reg_Crash, 3, 0, 1, 1)
        self.label_Reg_ScriptOutput = QtWidgets.QLabel(self.Tab_Generate)
        self.label_Reg_ScriptOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reg_ScriptOutput.setObjectName("label_Reg_ScriptOutput")
        self.gridLayout_2.addWidget(self.label_Reg_ScriptOutput, 2, 0, 1, 1)
        self.BT_Reg_ScriptOutput = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_ScriptOutput.setObjectName("BT_Reg_ScriptOutput")
        self.gridLayout_2.addWidget(self.BT_Reg_ScriptOutput, 2, 7, 1, 1)
        self.BT_Reg_ScriptTemplate = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_ScriptTemplate.setObjectName("BT_Reg_ScriptTemplate")
        self.gridLayout_2.addWidget(self.BT_Reg_ScriptTemplate, 0, 7, 1, 1)
        self.label_Reg_Template = QtWidgets.QLabel(self.Tab_Generate)
        self.label_Reg_Template.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reg_Template.setObjectName("label_Reg_Template")
        self.gridLayout_2.addWidget(self.label_Reg_Template, 0, 0, 1, 1)
        self.BT_Reg_Iitialize = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_Iitialize.setObjectName("BT_Reg_Iitialize")
        self.gridLayout_2.addWidget(self.BT_Reg_Iitialize, 1, 0, 1, 1)
        self.LE_Reg_ScirptOutput = QtWidgets.QLineEdit(self.Tab_Generate)
        self.LE_Reg_ScirptOutput.setDragEnabled(True)
        self.LE_Reg_ScirptOutput.setReadOnly(True)
        self.LE_Reg_ScirptOutput.setObjectName("LE_Reg_ScirptOutput")
        self.gridLayout_2.addWidget(self.LE_Reg_ScirptOutput, 2, 1, 1, 6)
        self.BT_Reg_RSU = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_RSU.setObjectName("BT_Reg_RSU")
        self.gridLayout_2.addWidget(self.BT_Reg_RSU, 5, 1, 1, 1)
        self.BT_Reg_Communication = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_Communication.setObjectName("BT_Reg_Communication")
        self.gridLayout_2.addWidget(self.BT_Reg_Communication, 5, 3, 1, 1)
        self.BT_Reg_Crash = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_Crash.setObjectName("BT_Reg_Crash")
        self.gridLayout_2.addWidget(self.BT_Reg_Crash, 5, 4, 1, 1)
        self.BT_Reg_IMU = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_IMU.setObjectName("BT_Reg_IMU")
        self.gridLayout_2.addWidget(self.BT_Reg_IMU, 5, 5, 1, 1)
        self.BT_Reg_Lamps = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_Lamps.setObjectName("BT_Reg_Lamps")
        self.gridLayout_2.addWidget(self.BT_Reg_Lamps, 5, 6, 1, 2)
        self.BT_Reg_SaveConfig = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_SaveConfig.setObjectName("BT_Reg_SaveConfig")
        self.gridLayout_2.addWidget(self.BT_Reg_SaveConfig, 9, 1, 1, 1)
        self.BT_Reg_LoadConfig = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_LoadConfig.setObjectName("BT_Reg_LoadConfig")
        self.gridLayout_2.addWidget(self.BT_Reg_LoadConfig, 9, 2, 1, 1)
        self.BT_Reg_OtherFault = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_OtherFault.setObjectName("BT_Reg_OtherFault")
        self.gridLayout_2.addWidget(self.BT_Reg_OtherFault, 6, 2, 1, 1)
        self.BT_Reg_CrashOutput = QtWidgets.QPushButton(self.Tab_Generate)
        self.BT_Reg_CrashOutput.setObjectName("BT_Reg_CrashOutput")
        self.gridLayout_2.addWidget(self.BT_Reg_CrashOutput, 6, 1, 1, 1)
        self.Tab_Regression.addTab(self.Tab_Generate, "")
        self.gridLayout_3.addWidget(self.Tab_Regression, 4, 0, 1, 3)
        self.LE_Reg_Excel = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LE_Reg_Excel.setFont(font)
        self.LE_Reg_Excel.setText("")
        self.LE_Reg_Excel.setDragEnabled(True)
        self.LE_Reg_Excel.setReadOnly(True)
        self.LE_Reg_Excel.setObjectName("LE_Reg_Excel")
        self.gridLayout_3.addWidget(self.LE_Reg_Excel, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 3)
        self.LE_Reg_Project = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LE_Reg_Project.setFont(font)
        self.LE_Reg_Project.setText("")
        self.LE_Reg_Project.setObjectName("LE_Reg_Project")
        self.gridLayout_3.addWidget(self.LE_Reg_Project, 1, 1, 1, 1)
        self.label_Reg_Project = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Reg_Project.setFont(font)
        self.label_Reg_Project.setObjectName("label_Reg_Project")
        self.gridLayout_3.addWidget(self.label_Reg_Project, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Regression)
        self.Tab_Regression.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Regression)

    def retranslateUi(self, Regression):
        _translate = QtCore.QCoreApplication.translate
        Regression.setWindowTitle(_translate("Regression", "Regression"))
        self.BT_Reg_Excel.setText(_translate("Regression", "Browse"))
        self.label_Reg_Excel.setText(_translate("Regression", "RegressionExcel:"))
        self.label_Reg_DBC.setText(_translate("Regression", " DBC files:"))
        self.LE_Reg_DBC.setPlaceholderText(_translate("Regression", "Select DBC file"))
        self.BT_Reg_DBC.setText(_translate("Regression", "Browse"))
        self.BT_Reg_ImportMsg.setText(_translate("Regression", "ImportMsg"))
        self.Tab_Regression.setTabText(self.Tab_Regression.indexOf(self.Tab_Import), _translate("Regression", "ImportData"))
        self.BT_Reg_DCS.setText(_translate("Regression", "DCS"))
        self.LE_Reg_IMUOutputPath.setPlaceholderText(_translate("Regression", "Select the folder to save the IMU data"))
        self.LE_Reg_ScriptTemplate.setPlaceholderText(_translate("Regression", "Select the folder where script template stored"))
        self.BT_Reg_CreateCurves.setText(_translate("Regression", "CreateCrashCurves"))
        self.BT_Reg_ENS.setText(_translate("Regression", "ENS"))
        self.BT_Reg_GenerateAll.setText(_translate("Regression", "GenerateAll"))
        self.BT_Reg_CrashOutputPath.setText(_translate("Regression", "Browse"))
        self.label_Reg_IMU.setText(_translate("Regression", "IMUData:"))
        self.BT_Reg_Loop.setText(_translate("Regression", "Loop"))
        self.BT_Reg_IMUOutputPath.setText(_translate("Regression", "Browse"))
        self.LE_Reg_CrashOutputPath.setPlaceholderText(_translate("Regression", "Select the folder to save CrashCurves"))
        self.label_Reg_Crash.setText(_translate("Regression", "CrashData:"))
        self.label_Reg_ScriptOutput.setText(_translate("Regression", "Scripts:"))
        self.BT_Reg_ScriptOutput.setText(_translate("Regression", "Browse"))
        self.BT_Reg_ScriptTemplate.setText(_translate("Regression", "Browse"))
        self.label_Reg_Template.setText(_translate("Regression", " Template Scripts:"))
        self.BT_Reg_Iitialize.setText(_translate("Regression", "Initialize"))
        self.LE_Reg_ScirptOutput.setPlaceholderText(_translate("Regression", "Select the folder  to save the scripts"))
        self.BT_Reg_RSU.setText(_translate("Regression", "RSU"))
        self.BT_Reg_Communication.setText(_translate("Regression", "Communication"))
        self.BT_Reg_Crash.setText(_translate("Regression", "Crash"))
        self.BT_Reg_IMU.setText(_translate("Regression", "IMU"))
        self.BT_Reg_Lamps.setText(_translate("Regression", "Lamps"))
        self.BT_Reg_SaveConfig.setText(_translate("Regression", "SaveConfig"))
        self.BT_Reg_LoadConfig.setText(_translate("Regression", "LoadConfig"))
        self.BT_Reg_OtherFault.setText(_translate("Regression", "OtherFault"))
        self.BT_Reg_CrashOutput.setText(_translate("Regression", "CrashOutput"))
        self.Tab_Regression.setTabText(self.Tab_Regression.indexOf(self.Tab_Generate), _translate("Regression", "GenerateScripts"))
        self.LE_Reg_Excel.setPlaceholderText(_translate("Regression", "Select the Regression Excel file"))
        self.LE_Reg_Project.setPlaceholderText(_translate("Regression", "Plese input the Project name"))
        self.label_Reg_Project.setText(_translate("Regression", "Project"))

