# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OtTool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OtTool(object):
    def setupUi(self, OtTool):
        OtTool.setObjectName("OtTool")
        OtTool.resize(911, 497)
        self.gridLayout_4 = QtWidgets.QGridLayout(OtTool)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(OtTool)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_AEFGenerate = QtWidgets.QWidget()
        self.tab_AEFGenerate.setObjectName("tab_AEFGenerate")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_AEFGenerate)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_AEFGen_BaseAEF = QtWidgets.QLabel(self.tab_AEFGenerate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_AEFGen_BaseAEF.setFont(font)
        self.label_AEFGen_BaseAEF.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AEFGen_BaseAEF.setObjectName("label_AEFGen_BaseAEF")
        self.gridLayout_2.addWidget(self.label_AEFGen_BaseAEF, 0, 0, 1, 1)
        self.LE_AEFGen_BaseAEF = QtWidgets.QLineEdit(self.tab_AEFGenerate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_AEFGen_BaseAEF.setFont(font)
        self.LE_AEFGen_BaseAEF.setReadOnly(True)
        self.LE_AEFGen_BaseAEF.setObjectName("LE_AEFGen_BaseAEF")
        self.gridLayout_2.addWidget(self.LE_AEFGen_BaseAEF, 0, 1, 1, 1)
        self.BT_AEFGen_BaseAEF = QtWidgets.QPushButton(self.tab_AEFGenerate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BT_AEFGen_BaseAEF.setFont(font)
        self.BT_AEFGen_BaseAEF.setObjectName("BT_AEFGen_BaseAEF")
        self.gridLayout_2.addWidget(self.BT_AEFGen_BaseAEF, 0, 2, 1, 1)
        self.label_AEFGen_AEFFiles = QtWidgets.QLabel(self.tab_AEFGenerate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_AEFGen_AEFFiles.setFont(font)
        self.label_AEFGen_AEFFiles.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AEFGen_AEFFiles.setObjectName("label_AEFGen_AEFFiles")
        self.gridLayout_2.addWidget(self.label_AEFGen_AEFFiles, 1, 0, 1, 1)
        self.TextB_AEFGen_AEFFiles = QtWidgets.QTextBrowser(self.tab_AEFGenerate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TextB_AEFGen_AEFFiles.setFont(font)
        self.TextB_AEFGen_AEFFiles.setObjectName("TextB_AEFGen_AEFFiles")
        self.gridLayout_2.addWidget(self.TextB_AEFGen_AEFFiles, 1, 1, 2, 1)
        self.BT_AEFGen_AEFGenerate = QtWidgets.QPushButton(self.tab_AEFGenerate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BT_AEFGen_AEFGenerate.setFont(font)
        self.BT_AEFGen_AEFGenerate.setObjectName("BT_AEFGen_AEFGenerate")
        self.gridLayout_2.addWidget(self.BT_AEFGen_AEFGenerate, 3, 0, 1, 1)
        self.BT_AEFGen_AEFFiles = QtWidgets.QPushButton(self.tab_AEFGenerate)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BT_AEFGen_AEFFiles.setFont(font)
        self.BT_AEFGen_AEFFiles.setObjectName("BT_AEFGen_AEFFiles")
        self.gridLayout_2.addWidget(self.BT_AEFGen_AEFFiles, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_AEFGenerate, "")
        self.tab_Sym2Ts = QtWidgets.QWidget()
        self.tab_Sym2Ts.setObjectName("tab_Sym2Ts")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_Sym2Ts)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_Sym2Ts_Sym = QtWidgets.QLabel(self.tab_Sym2Ts)
        self.label_Sym2Ts_Sym.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Sym2Ts_Sym.setObjectName("label_Sym2Ts_Sym")
        self.gridLayout_3.addWidget(self.label_Sym2Ts_Sym, 0, 0, 1, 1)
        self.LE_Sym2Ts_Sym = QtWidgets.QLineEdit(self.tab_Sym2Ts)
        self.LE_Sym2Ts_Sym.setReadOnly(True)
        self.LE_Sym2Ts_Sym.setObjectName("LE_Sym2Ts_Sym")
        self.gridLayout_3.addWidget(self.LE_Sym2Ts_Sym, 0, 1, 1, 1)
        self.BT_Sym2Ts_Sym = QtWidgets.QPushButton(self.tab_Sym2Ts)
        self.BT_Sym2Ts_Sym.setObjectName("BT_Sym2Ts_Sym")
        self.gridLayout_3.addWidget(self.BT_Sym2Ts_Sym, 0, 2, 1, 1)
        self.label_Sym2Ts_Output = QtWidgets.QLabel(self.tab_Sym2Ts)
        self.label_Sym2Ts_Output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Sym2Ts_Output.setObjectName("label_Sym2Ts_Output")
        self.gridLayout_3.addWidget(self.label_Sym2Ts_Output, 1, 0, 1, 1)
        self.LE_Sym2Ts_Output = QtWidgets.QLineEdit(self.tab_Sym2Ts)
        self.LE_Sym2Ts_Output.setReadOnly(False)
        self.LE_Sym2Ts_Output.setObjectName("LE_Sym2Ts_Output")
        self.gridLayout_3.addWidget(self.LE_Sym2Ts_Output, 1, 1, 1, 1)
        self.BT_Sym2Ts_GenerateSymTs = QtWidgets.QPushButton(self.tab_Sym2Ts)
        self.BT_Sym2Ts_GenerateSymTs.setObjectName("BT_Sym2Ts_GenerateSymTs")
        self.gridLayout_3.addWidget(self.BT_Sym2Ts_GenerateSymTs, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_Sym2Ts, "")
        self.tab_DictGenerate = QtWidgets.QWidget()
        self.tab_DictGenerate.setObjectName("tab_DictGenerate")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_DictGenerate)
        self.gridLayout.setObjectName("gridLayout")
        self.label_DictGen_Excel = QtWidgets.QLabel(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_DictGen_Excel.setFont(font)
        self.label_DictGen_Excel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DictGen_Excel.setObjectName("label_DictGen_Excel")
        self.gridLayout.addWidget(self.label_DictGen_Excel, 0, 0, 1, 1)
        self.LE_DictGen_Excel = QtWidgets.QLineEdit(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.LE_DictGen_Excel.setFont(font)
        self.LE_DictGen_Excel.setText("")
        self.LE_DictGen_Excel.setReadOnly(True)
        self.LE_DictGen_Excel.setObjectName("LE_DictGen_Excel")
        self.gridLayout.addWidget(self.LE_DictGen_Excel, 0, 1, 1, 1)
        self.BT_DictGen_Excel = QtWidgets.QPushButton(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.BT_DictGen_Excel.setFont(font)
        self.BT_DictGen_Excel.setObjectName("BT_DictGen_Excel")
        self.gridLayout.addWidget(self.BT_DictGen_Excel, 0, 2, 1, 1)
        self.label_DictGen_Sheet = QtWidgets.QLabel(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_DictGen_Sheet.setFont(font)
        self.label_DictGen_Sheet.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DictGen_Sheet.setObjectName("label_DictGen_Sheet")
        self.gridLayout.addWidget(self.label_DictGen_Sheet, 1, 0, 1, 1)
        self.LE_DictGen_Sheet = QtWidgets.QLineEdit(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.LE_DictGen_Sheet.setFont(font)
        self.LE_DictGen_Sheet.setText("")
        self.LE_DictGen_Sheet.setObjectName("LE_DictGen_Sheet")
        self.gridLayout.addWidget(self.LE_DictGen_Sheet, 1, 1, 1, 1)
        self.label_DictGen_Key = QtWidgets.QLabel(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_DictGen_Key.setFont(font)
        self.label_DictGen_Key.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DictGen_Key.setObjectName("label_DictGen_Key")
        self.gridLayout.addWidget(self.label_DictGen_Key, 2, 0, 1, 1)
        self.LE_DictGen_Key = QtWidgets.QLineEdit(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.LE_DictGen_Key.setFont(font)
        self.LE_DictGen_Key.setObjectName("LE_DictGen_Key")
        self.gridLayout.addWidget(self.LE_DictGen_Key, 2, 1, 1, 1)
        self.label_DictGen_Values = QtWidgets.QLabel(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_DictGen_Values.setFont(font)
        self.label_DictGen_Values.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DictGen_Values.setObjectName("label_DictGen_Values")
        self.gridLayout.addWidget(self.label_DictGen_Values, 3, 0, 1, 1)
        self.LE_DictGen_Values = QtWidgets.QLineEdit(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.LE_DictGen_Values.setFont(font)
        self.LE_DictGen_Values.setObjectName("LE_DictGen_Values")
        self.gridLayout.addWidget(self.LE_DictGen_Values, 3, 1, 1, 1)
        self.label_DictGen_OutPut = QtWidgets.QLabel(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_DictGen_OutPut.setFont(font)
        self.label_DictGen_OutPut.setAlignment(QtCore.Qt.AlignCenter)
        self.label_DictGen_OutPut.setObjectName("label_DictGen_OutPut")
        self.gridLayout.addWidget(self.label_DictGen_OutPut, 4, 0, 1, 1)
        self.LE_DictGen_Output = QtWidgets.QLineEdit(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.LE_DictGen_Output.setFont(font)
        self.LE_DictGen_Output.setObjectName("LE_DictGen_Output")
        self.gridLayout.addWidget(self.LE_DictGen_Output, 4, 1, 1, 1)
        self.BT_DictGen_GenerateDict = QtWidgets.QPushButton(self.tab_DictGenerate)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.BT_DictGen_GenerateDict.setFont(font)
        self.BT_DictGen_GenerateDict.setObjectName("BT_DictGen_GenerateDict")
        self.gridLayout.addWidget(self.BT_DictGen_GenerateDict, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab_DictGenerate, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(OtTool)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(OtTool)

    def retranslateUi(self, OtTool):
        _translate = QtCore.QCoreApplication.translate
        OtTool.setWindowTitle(_translate("OtTool", "OtTool"))
        self.label_AEFGen_BaseAEF.setText(_translate("OtTool", "BaseAEF:"))
        self.LE_AEFGen_BaseAEF.setPlaceholderText(_translate("OtTool", "Select the base AEF file"))
        self.BT_AEFGen_BaseAEF.setText(_translate("OtTool", "Browse"))
        self.label_AEFGen_AEFFiles.setText(_translate("OtTool", "AEF Files:"))
        self.TextB_AEFGen_AEFFiles.setPlaceholderText(_translate("OtTool", "Selelct the AEF files"))
        self.BT_AEFGen_AEFGenerate.setText(_translate("OtTool", "AEFGenerate:"))
        self.BT_AEFGen_AEFFiles.setText(_translate("OtTool", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_AEFGenerate), _translate("OtTool", "AEFGenerate"))
        self.label_Sym2Ts_Sym.setText(_translate("OtTool", "SymFile:"))
        self.LE_Sym2Ts_Sym.setPlaceholderText(_translate("OtTool", "Select the Sym file"))
        self.BT_Sym2Ts_Sym.setText(_translate("OtTool", "Browse"))
        self.label_Sym2Ts_Output.setText(_translate("OtTool", "OutPut:"))
        self.LE_Sym2Ts_Output.setPlaceholderText(_translate("OtTool", "Fill the Ts Name to save"))
        self.BT_Sym2Ts_GenerateSymTs.setText(_translate("OtTool", "GenerateSymTs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Sym2Ts), _translate("OtTool", "Sym2Ts"))
        self.label_DictGen_Excel.setText(_translate("OtTool", "Excel:"))
        self.LE_DictGen_Excel.setPlaceholderText(_translate("OtTool", "Select an Excel to generate dict"))
        self.BT_DictGen_Excel.setText(_translate("OtTool", "Browse"))
        self.label_DictGen_Sheet.setText(_translate("OtTool", "SheetName:"))
        self.LE_DictGen_Sheet.setPlaceholderText(_translate("OtTool", "Fill in the sheet name"))
        self.label_DictGen_Key.setText(_translate("OtTool", "Key:"))
        self.LE_DictGen_Key.setPlaceholderText(_translate("OtTool", "Fill in the Row title as Key"))
        self.label_DictGen_Values.setText(_translate("OtTool", "Values:"))
        self.LE_DictGen_Values.setPlaceholderText(_translate("OtTool", "Fill in the Row titles as Values"))
        self.label_DictGen_OutPut.setText(_translate("OtTool", "Output"))
        self.LE_DictGen_Output.setPlaceholderText(_translate("OtTool", "Fill in the Ts name to save"))
        self.BT_DictGen_GenerateDict.setText(_translate("OtTool", "GenerateDict"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DictGenerate), _translate("OtTool", "DictGenerate"))

